### ISSUE TITLE
Tinker create file not working

### ISSUE THREAD

**Issue by yukaylaw** [markperri/chemcompute_issues#2]
It appears that Tinker, when I try and put in .key, .prm, and .xyz files (with the "Select your own files" mode it won't work - specifically nothing seems to happen when I select the files, and then when I submit the job it stalls.
Could you please advise?
Thanks,

**Comment by markperri** [comment]
Hi Yukaylaw,

Sorry about that.  I did some refactoring a while back and didn't catch that.  I've fixed it now, let me know how it goes.

I've been focusing on NAMD, so Tinker hasn't gotten much attention.  I almost deleted it off the site, but I decided to keep it until I couldn't maintain it anymore.

Thanks,
Mark

**Comment by yukaylaw** [comment]
Thanks!
I understand the logic of removing Tinker.  I will note that the equivalent feature - searching for and running a small molecule - doesn't seem to work for NAMD either.  I didn't see a difference here with what was done.

**Comment by markperri** [comment]
You might have to refresh your cache (ctrl-F5) to see the changes.  Which molecule were you trying to use with NAMD?

**Comment by yukaylaw** [comment]
Lovely.  Thanks!  I was trying to use alanine with NAMD (but it also failed with dialanine).
I think I can make the thing work with TINKER, which would be great.

**Comment by markperri** [comment]
It looks like something is wrong with NAMD on Jetstream, I'll check it out.  Try Expanse instead.

**Comment by markperri** [comment]
There was an auto update that broke access to the filesystem for one of the packages.  I fixed it, so NAMD should work on all systems.  If you have a large molecule you can try expanse-gpu.  Let me know if you find any other problems.
Thanks,
Mark
