### ISSUE TITLE
GAMESS experiments / vibrational spectra, file extension

### ISSUE THREAD

**Issue by nbehrnd** [markperri/chemcompute_issues#5]
For the output file of GAMESS (US), I would like to suggest `.gamess` as file extension.

At present, the downloadable record of GAMESS (US) output uses the file extension `.stdout`.  Instead, I would like to suggest either one of `.gam`, `.gamess`, `.gamout` as listed running

```shell
obabel -L formats | grep -i gamess
```

and documented in the documentation of [OpenBabel](https://github.com/openbabel/openbabel) (revision July 14, 2023 [section 18.4.21](https://open-babel.readthedocs.io/en/latest/FileFormats/GAMESS_Output.html)).

Else, I suggest the generic `.out` (cf. [section 18.2.5](https://open-babel.readthedocs.io/en/latest/FileFormats/Generic_Output_file_format.html) in OpenBabel's documentation) though this one feels a little bit *too generic* vs. records generated by other programs.

In the long run, this change would ease work down the road with OpenBabel because by default the program infers the file format from the file extension.  Then an explicit flag on the CLI about the input format `-igamess` were not required, either.  Second, the adjusted name convention would allow the file managers of GUIs recognize these files easier; beside `obgui`, I noticed this while working with [Avogadro2](https://github.com/OpenChemistry/avogadroapp).

Because there is no longer a constraint to three characters (max) as file extension, I have a little preference for `.gamess` to i) identify/sort/filter files in a file manager by this criterion regardless of their file content and ii) because it is Avogadro2's preferred file extension specifically for GAMESS (US) output.

**Comment by markperri** [comment]
You can now download job output as .gamess if you select .gamess in the dropdown box.  It'll only work for new jobs though, not old jobs.
