### ISSUE TITLE
Psi4 not working on Expanse

### ISSUE THREAD

**Issue by squeyroy** [markperri/chemcompute_issues#8]
When I launch a Psi4 job setting "expanse" as computercluster, after completion, the field "Result" remains blank on my dashboard, while status is "COMPLETE".
In the graphical interface, the Psi4.out is not available. In slurm log, I can read "error parsing ./Psi4.out". 

If I launch the same job setting "jetstream2" or "bridges2" as computer cluster, then I have access to the output (and the "Result" is "success").

**Comment by markperri** [comment]
Thank you for letting me know.  It looks like expanse upgraded a module on their system and removed the old version.  I upgraded mine to match.  It should be working now, let me know if you have any more issues.
